spring:
  thymeleaf:
    mode: HTML
  profiles:
    active: dev

mybatis:
  type-aliases-package: com.star.entity
  mapper-locations: classpath:mapper/*.xml
  configuration:
    map-underscore-to-camel-case: true

comment.avatar: /images/avatar.png
message.avatar: /images/avatar.png

#配置mapper xml文件的路径
mybatis-plus:
  mapper-locations: classpath*:mapper/*.xml,classpath*:mapper/**/*Mapper.xml





